---
title: "Main"
output: pdf_document
---

```{r setup, include=FALSE}
player_team_lol_data <- read.csv('player_team_lol_data.csv', sep=',')
data_lol <- read.csv('player_team_lol_data.csv', sep=',')
library(questionr)
library(dplyr)
```

## Test

```{r}
median(data_lol$deaths1)
```

## Endroit où on à plus ,de chance de mourir
```{r}
d <- data
deaths = cbind(d$deaths1, d$deaths2, d$deaths3, d$deaths4, d$deaths5, d$deaths6)
lane = cbind(d$lane1, d$lane2, d$lane3, d$lane4, d$lane5, d$lane6)

freq(lane, cum=TRUE)
boxplot(deaths ~ lane)

```
=> Pas de corélation


# Quel champion chez les gagnants
```{r}
d <- data_lol

# Get winers team
win1 = filter(d, winTeam1 == " Win")
win2 = filter(d, winTeam2 == " Win")
# Get winers champions
winChampTeam1 = cbind(win1$championID1, win1$championID2, win1$championID3, win1$championID4, win1$championID5)
winChampTeam2 = c(win2$championID6, win2$championID7, win2$championID8, win2$championID9, win2$championID10)
winChampGlobal = c(winChampTeam1, winChampTeam2)
freq(winChampGlobal, sort="dec")
```

# Quel champion tue le plus
```{r}
d <- data_lol



ids = c()
kills = c()
for (i in 1:10) {
  ids = c(ids, d[,paste('championID', i, sep="")])
  kills = c(kills, d[,paste('kills', i, sep="")])
}

killPerChamp = matrix(c(ids, kills), ncol = 2)
View(killPerChamp)

#chisq.test(killPerChamp)$p.value

# ! Ca sert à rien, psq on a as le mm nombre de champion
```

# Est ce que tuer les minions c'est vraiment util
```{r}

win1 = filter(d, winTeam1 == " Win")
win2 = filter(d, winTeam2 == " Win")

minionsKillWin = c()
minionsKillLose = c()
for (i in 1:5) {
  #minionsKillWin = c(minionsKillWin, d[,paste('minionsKill', i, sep="")])
  minionsKillLose = c(minionsKillLose, d[,paste('minionsKill', i + 5, sep="")])
}

minionsKillWin = sum(win1$minionsKill1, win1$minionsKill2)

```
=======
## Test

``` {r}
data_test = data_lol[, c("kills1", "kills2", "kills3", "kills4", "kills5", "winTeam1")]
data_sum = data_test %>% replace(is.na(.), 0) %>% mutate(sum = rowSums(.[1:5]))
boxplot(data_sum$sum ~ data_sum$winTeam1)

```
```{r}
data_test_2 = data_lol[, c("kills6", "kills7", "kills8", "kills9", "kills10", "winTeam2")]
data_sum_2 = data_test_2 %>% replace(is.na(.), 0) %>% mutate(sum = rowSums(.[1:5]))
boxplot(data_sum_2$sum ~ data_sum_2$winTeam2)
```


``` {r}
# récupération du nombre de kills des parties gagnante
win1 <- filter(data_lol, winTeam1 == " Win")[,c( "kills1", "kills2", "kills3", "kills4", "kills5")]
win2 <- filter(data_lol, winTeam2 == " Win")[,c( "kills6", "kills7", "kills8", "kills9", "kills10")]
names(win2) <- c( "kills1", "kills2", "kills3", "kills4", "kills5")
win <- rbind(win1, win2)
killsWin <- rowSums(win)

# récupération du nombre de kills des parties perdante
fail1 <- filter(data_lol, winTeam1 == " Fail")[,c( "kills1", "kills2", "kills3", "kills4", "kills5")]
fail2 <- filter(data_lol, winTeam2 == " Fail")[,c( "kills6", "kills7", "kills8", "kills9", "kills10")]
names(fail2) <- c( "kills1", "kills2", "kills3", "kills4", "kills5")
fail <- rbind(fail1, fail2)
killsFail <- rowSums(fail)

# test
mean(killsWin)
mean(killsFail)
```



